### ISSUE TITLE
Graduate cap request

### ISSUE THREAD

**Issue by opinner** [EagleoutIce/tikzpingus#273]
**How should the clothes look?**
I would like to see a graduate cap, similar to _Graduate duck_ from the `tikzducks` package. 

**Should it look differently, depending other extras?**
In the best case, hat and tassel color could be specified individually, but I would be more than happy with just a default cap.

**Is there already a similar cloth?**
I don't think there is one, the existing cap is not close. 

**Additional context**
graduate duck from the tikzduck package 
![grafik](https://github.com/user-attachments/assets/34f65d8c-8a8f-4de6-a286-d2dbd77d5f04)

Maybe I will try it myself, but my art experience with tikz is very limited

**Comment by EagleoutIce** [comment]
I will see that i get to it if you don't want! :D
